(ns hashed-colls)

(defn -main []
  (def players #{"Alice", "Bob", "Kelly"})
  (println (conj players "Fred"))
  (println (disj players "Bob" "Sal"))
  (println (contains? players "Kelly"))
  (println (conj (sorted-set) "Bravo" "Charlie" "Sigma" "Alpha"))
  (def new-players ["Tim" "Sue" "Greg"])
  (println (into players new-players))
  (def scores {"Fred" 1400, "Bob" 1240, "Angela" 1024})
  (println (assoc scores "Sally" 0))
  (println (assoc scores "Bob" 0))
  (println (dissoc scores "Bob"))
  (println (get scores "Angela"))
  (def directions {:north 0, :east 1, :south 2, :west 3})
  (println (directions :north))
  ;; (def bad-lookup-map nil)
  ;; (bad-lookup-map :foo)
  (println (get scores "Sam" 0))
  (println (directions :northwest -1))
  (println (contains? scores "Fred"))
  (println (find scores "Fred"))
  (println (keys scores))
  (println (vals scores))
  (println (zipmap players (repeat 0)))
  (println (into {} (map (fn [player] [player 0]) players)))
  (println (reduce (fn [m player] (assoc m player 0)) {} players))
  (def new-scores {"Angela" 300, "Jeff" 900})
  (println (merge scores new-scores))
  (println (merge-with + scores new-scores))
  (def sm (sorted-map "Bravo" 204 "Alpha" 35 "Sigma" 99 "Charlie" 100))
  (println (keys sm))
  (println (vals sm))
  (def person {:first-name "Kelly", :last-name "Keen", :age 32, :occupation "Programmer"})
  (println (person :occupation))
  (println (:occupation person))
  (println (:favarite-color person "beige"))
  (println (assoc person :occupation "Baker"))
  (println (dissoc person :age))
  (def company {:name "WidgetCo" :address {:street "123 Main st" :city "SpringField" :state "IL"}})
  (println (get-in company [:address :city]))
  (println (assoc-in company [:address :street] "303 Broadway"))
  (defrecord Person [first-name last-name age occupation])
  (def kelly (->Person "Kelly" "Keen" 32 "Programmer"))
  (println kelly)
  (def kelly2 (map->Person {:first-name "Kelly" :last-name "Keen" :age 32 :occupation "Programmer"}))
  (println kelly2)
  (println (:occupation kelly))
  (println))
